from django.db import models

class Civilstudent(models.Model):
    name=models.CharField(max_length=50)
    fname=models.CharField(max_length=50)
    course=models.CharField(max_length=50)
    rolleno=models.CharField(max_length=50,primary_key=True)
    secation=models.CharField(max_length=50)
    fsub=models.CharField(max_length=50)
    ssub=models.CharField(max_length=50)
    tsub=models.CharField(max_length=50)
    fosub=models.CharField(max_length=50)
    Attendence=models.DecimalField(max_digits=4,decimal_places=2)
class Csestudent(models.Model):
    name=models.CharField(max_length=50)
    fname=models.CharField(max_length=50)
    course=models.CharField(max_length=50)
    rolleno=models.CharField(max_length=50,primary_key=True)
    secation=models.CharField(max_length=50)
    fsub=models.CharField(max_length=50)
    ssub=models.CharField(max_length=50)
    tsub=models.CharField(max_length=50)
    fosub=models.CharField(max_length=50)
    Attendence=models.DecimalField(max_digits=4,decimal_places=2)
class Ecestudent(models.Model):
    name=models.CharField(max_length=50)
    fname=models.CharField(max_length=50)
    course=models.CharField(max_length=50)
    rolleno=models.CharField(max_length=50,primary_key=True)
    secation=models.CharField(max_length=50)
    fsub=models.CharField(max_length=50)
    ssub=models.CharField(max_length=50)
    tsub=models.CharField(max_length=50)
    fosub=models.CharField(max_length=50)
    Attendence=models.DecimalField(max_digits=4,decimal_places=2)
class Eeestudent(models.Model):
    name=models.CharField(max_length=50)
    fname=models.CharField(max_length=50)
    course=models.CharField(max_length=50)
    rolleno=models.CharField(max_length=50,primary_key=True)
    secation=models.CharField(max_length=50)
    fsub=models.CharField(max_length=50)
    ssub=models.CharField(max_length=50)
    tsub=models.CharField(max_length=50)
    fosub=models.CharField(max_length=50)
    Attendence=models.DecimalField(max_digits=4,decimal_places=2)
class Mestudent(models.Model):
    name=models.CharField(max_length=50)
    fname=models.CharField(max_length=50)
    course=models.CharField(max_length=50)
    rolleno=models.CharField(max_length=50,primary_key=True)
    secation=models.CharField(max_length=50)
    fsub=models.CharField(max_length=50)
    ssub=models.CharField(max_length=50)
    tsub=models.CharField(max_length=50)
    fosub=models.CharField(max_length=50)
    Attendence=models.DecimalField(max_digits=4,decimal_places=2)

class Civilfaculty(models.Model):
    name=models.CharField(max_length=50)
    idno=models.IntegerField(primary_key=True)
    qualiufi=models.CharField(max_length=50)
    reasearch=models.CharField(max_length=50)
    exp=models.IntegerField()
    dob=models.DateField()
class CSE(models.Model):
    name=models.CharField(max_length=50)
    idno=models.IntegerField(primary_key=True)
    qualiufi=models.CharField(max_length=50)
    reasearch=models.CharField(max_length=50)
    exp=models.IntegerField()
    dob=models.DateField()

class ECE(models.Model):
    name=models.CharField(max_length=50)
    idno=models.IntegerField(primary_key=True)
    qualiufi=models.CharField(max_length=50)
    reasearch=models.CharField(max_length=50)
    exp=models.IntegerField()
    dob=models.DateField()

class EEE(models.Model):
    name=models.CharField(max_length=50)
    idno=models.IntegerField(primary_key=True)
    qualiufi=models.CharField(max_length=50)
    reasearch=models.CharField(max_length=50)
    exp=models.IntegerField()
    dob=models.DateField()

class ME(models.Model):
    name=models.CharField(max_length=50)
    idno=models.IntegerField(primary_key=True)
    qualiufi=models.CharField(max_length=50)
    reasearch=models.CharField(max_length=50)
    exp=models.IntegerField()
    dob=models.DateField()

class usermessage(models.Model):
    name=models.CharField(max_length=70)
    contact=models.IntegerField()
    email=models.EmailField(max_length=50,primary_key=True)
    massege=models.CharField(max_length=150)