# Generated by Django 2.1.3 on 2018-12-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20181211_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civil',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ECE',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EEE',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ME',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rolleno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secation', models.CharField(max_length=50)),
                ('fsemister', models.CharField(max_length=50)),
                ('ssemister', models.CharField(max_length=50)),
                ('tsemister', models.CharField(max_length=50)),
                ('fosemister', models.CharField(max_length=50)),
                ('fsub', models.CharField(max_length=50)),
                ('ssub', models.CharField(max_length=50)),
                ('tsub', models.CharField(max_length=50)),
                ('fosub', models.CharField(max_length=50)),
                ('Attendence', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
