# Generated by Django 2.1.3 on 2018-12-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_civil_cse_ece_eee_me_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Civil',
            new_name='Civilfaculty',
        ),
    ]
