# Generated by Django 2.1.3 on 2018-12-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181211_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Civilfaculty',
        ),
        migrations.DeleteModel(
            name='CSE',
        ),
        migrations.DeleteModel(
            name='ECE',
        ),
        migrations.DeleteModel(
            name='EEE',
        ),
        migrations.DeleteModel(
            name='ME',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
