# Generated by Django 2.1.3 on 2018-12-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_civilfaculty_civilstudent_cse_csestudent_ece_ecestudent_eee_eeestudent_me_mestudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Civilfaculty',
        ),
        migrations.DeleteModel(
            name='Civilstudent',
        ),
        migrations.DeleteModel(
            name='CSE',
        ),
        migrations.DeleteModel(
            name='Csestudent',
        ),
        migrations.DeleteModel(
            name='ECE',
        ),
        migrations.DeleteModel(
            name='Ecestudent',
        ),
        migrations.DeleteModel(
            name='EEE',
        ),
        migrations.DeleteModel(
            name='Eeestudent',
        ),
        migrations.DeleteModel(
            name='ME',
        ),
        migrations.DeleteModel(
            name='Mestudent',
        ),
    ]
