# Generated by Django 2.1.3 on 2018-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_civilfaculty_civilstudent_cse_csestudent_ece_ecestudent_eee_eeestudent_me_mestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('massege', models.CharField(max_length=150)),
            ],
        ),
    ]
