# Generated by Django 2.1.3 on 2018-12-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181215_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Civilfaculty',
        ),
        migrations.DeleteModel(
            name='Civilstudent',
        ),
        migrations.DeleteModel(
            name='CSE',
        ),
        migrations.DeleteModel(
            name='Csestudent',
        ),
        migrations.DeleteModel(
            name='ECE',
        ),
        migrations.DeleteModel(
            name='Ecestudent',
        ),
        migrations.DeleteModel(
            name='EEE',
        ),
        migrations.DeleteModel(
            name='Eeestudent',
        ),
        migrations.DeleteModel(
            name='ME',
        ),
        migrations.DeleteModel(
            name='Mestudent',
        ),
        migrations.DeleteModel(
            name='usermessage',
        ),
    ]
