# Generated by Django 2.1.3 on 2018-12-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0011_auto_20181218_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilfaculty',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Civilstudent',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rolleno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secation', models.CharField(max_length=50)),
                ('fsub', models.CharField(max_length=50)),
                ('ssub', models.CharField(max_length=50)),
                ('tsub', models.CharField(max_length=50)),
                ('fosub', models.CharField(max_length=50)),
                ('Attendence', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Csestudent',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rolleno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secation', models.CharField(max_length=50)),
                ('fsub', models.CharField(max_length=50)),
                ('ssub', models.CharField(max_length=50)),
                ('tsub', models.CharField(max_length=50)),
                ('fosub', models.CharField(max_length=50)),
                ('Attendence', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ECE',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecestudent',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rolleno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secation', models.CharField(max_length=50)),
                ('fsub', models.CharField(max_length=50)),
                ('ssub', models.CharField(max_length=50)),
                ('tsub', models.CharField(max_length=50)),
                ('fosub', models.CharField(max_length=50)),
                ('Attendence', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='EEE',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Eeestudent',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rolleno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secation', models.CharField(max_length=50)),
                ('fsub', models.CharField(max_length=50)),
                ('ssub', models.CharField(max_length=50)),
                ('tsub', models.CharField(max_length=50)),
                ('fosub', models.CharField(max_length=50)),
                ('Attendence', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ME',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('qualiufi', models.CharField(max_length=50)),
                ('reasearch', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mestudent',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('rolleno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secation', models.CharField(max_length=50)),
                ('fsub', models.CharField(max_length=50)),
                ('ssub', models.CharField(max_length=50)),
                ('tsub', models.CharField(max_length=50)),
                ('fosub', models.CharField(max_length=50)),
                ('Attendence', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='usermessage',
            fields=[
                ('name', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('massege', models.CharField(max_length=150)),
            ],
        ),
    ]
